apiVersion: batch/v1
kind: CronJob
metadata:
  name: xworkflow1-go-app-cronjob
spec:
  schedule: "*/1 * * * *"  # Run every 1 minute
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: my-go-app
            image: murtazashah46/kubecost-cronjob:latest #murtazashah46/xworkflow1:latest
          restartPolicy: OnFailure
