apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secrets
type: Opaque
data:
  mongodb-root-username: YWRtaW4= # base64 for 'admin'
  mongodb-root-password: YWRtaW4xMjM= # base64 for 'admin123'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
data:
  mongoInitDbDatabase: k8sData
