apiVersion: v1
kind: ConfigMap
metadata:
  name: query-config
data:
  values.yaml: |
    workflows:
    - data_source: kubecost
      name: workflow1
      robusta_playbook: nil
      scrape_data: nodes

    - data_source: kubecost
      name: workflow2
      robusta_playbook: xyz
      scrape_data: unclaimedvolume

    - data_source: custom_source
      name: workflow3
      robusta_playbook: custom_playbook
      scrape_data: custom_data
