version: '3.3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: k8sData
    volumes:
      - mongodb-data:/data/db
    network_mode: "host"
    
  query_pod:
    build:
      context: ./
    container_name: query_pod
    depends_on:
      - mongodb
    environment:
      MONGODB_HOSTNAME: localhost
      MONGODB_USERNAME: admin
      MONGODB_PASSWORD: admin123
      MONGODB_DATABASE: k8sData
    volumes:
      - ./values.yaml:/app/config/values.yaml

    network_mode: "host"

volumes:
  mongodb-data:
