apiVersion: v1
kind: Service
metadata:
  name: xworkflow-mongodb
  namespace: xworkflow1
spec:
  selector:
    app: mongo
  clusterIP: None  # Headless service does not have a cluster IP
  ports:
  - port: 27017
    targetPort: 27017  # Default mongodb port
