apiVersion: v1
kind: Service
metadata:
  name: unclaimed-pv-api-service
  namespace: xworkflow1
spec:
  selector:
    app: unclaimed-pv-api
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: NodePort
